name: Lab Workflow
on:
  workflow_dispatch:  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [8.0, 9.0]
    
    steps:
      - name: Run-time Context
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Author: ${{ github.actor }}"
          if [ ${{ github.event_name }} == 'pull_request' ]; then
            echo "Pr-number: ${{ github.event.pull_request.number }}"
          elif [ ${{ github.event_name }} == 'push' ]; then
            echo "Branch: ${{ github.ref }}"
            echo "Commit message: ${{ github.event.head_commit.message }}"
          fi
          
      - name: Checkout code
        uses: actions/checkout@v5.0.0
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: ${{ matrix.version }}

      - name: Build Solution
        run: dotnet build

      - name: Run Test If Build Succeeds
        if: success()
        run: dotnet test
